### ISSUE TITLE
Some guidance on the setting up lookup tables in the SQLite database?

### ISSUE THREAD

**Issue by ghost** [NYNatHeritage/Regional_SDM#81]
Maybe I overlooked it, but I haven't seen any steps for setting up the lookup tables in the SQLite database. Maybe this could be added to the Wiki?

**Comment by tghoward** [comment]
Good question. The SQLite database is definitely intertwined with the scripts and a necessary part. We weren't including it in the repository because, not being a text file, version tracking doesn't work the same way and it may make the size of the repository increase a bunch. Nevertheless, it seems like it is time to add it. I'll do that either today or tomorrow.

**Comment by tghoward** [comment]
I think I've found a way to have our cake and eat it too. Since we would want to store a reference version of the DB in this repository I found a way to dump it to text file and also recreate the full DB from the same text file. That's what I've done here: there is now a script for creating the sqlite DB from a text dump that I've also placed in the repository. 

I'm not trying to make it difficult for you so I'll send you the DB directly if you send me your email address offline. 
Tim
